# Generated by Django 4.2.20 on 2025-04-11 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.CharField(max_length=255)),
                ('industry', models.CharField(blank=True, max_length=255, null=True)),
                ('sales', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_funding', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('homepage', models.URLField(blank=True, null=True)),
                ('key_executive', models.CharField(blank=True, max_length=255, null=True)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Company Data',
            },
        ),
        migrations.CreateModel(
            name='LeadProspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance_score', models.FloatField(default=0.0)),
                ('reasoning', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prospect_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_leads', to='scout_agent.companydata')),
                ('source_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discovered_leads', to='scout_agent.companydata')),
            ],
        ),
    ]
