# Generated by Django 4.2.20 on 2025-04-15 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scout_agent', '0002_companyprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_areas', models.TextField(blank=True, null=True)),
                ('products_services', models.TextField(blank=True, null=True)),
                ('core_technologies', models.TextField(blank=True, null=True)),
                ('competitive_advantages', models.TextField(blank=True, null=True)),
                ('target_markets', models.TextField(blank=True, null=True)),
                ('key_customers', models.TextField(blank=True, null=True)),
                ('recent_achievements', models.TextField(blank=True, null=True)),
                ('growth_potential', models.TextField(blank=True, null=True)),
                ('funding_status', models.TextField(blank=True, null=True)),
                ('investment_plans', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_analyses', to='scout_agent.companydata')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='scout_agent.companyprofile')),
            ],
            options={
                'verbose_name': 'PDF 분석',
                'verbose_name_plural': 'PDF 분석들',
                'unique_together': {('company', 'profile')},
            },
        ),
    ]
