# Generated by Django 4.2.20 on 2025-04-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout_agent', '0003_pdfanalysis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdfanalysis',
            old_name='business_areas',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='pdfanalysis',
            old_name='competitive_advantages',
            new_name='business_model',
        ),
        migrations.RenameField(
            model_name='pdfanalysis',
            old_name='core_technologies',
            new_name='company_description',
        ),
        migrations.RenameField(
            model_name='pdfanalysis',
            old_name='funding_status',
            new_name='competitors',
        ),
        migrations.RenameField(
            model_name='pdfanalysis',
            old_name='growth_potential',
            new_name='strengths',
        ),
        migrations.RenameField(
            model_name='pdfanalysis',
            old_name='investment_plans',
            new_name='target_customers',
        ),
        migrations.RemoveField(
            model_name='pdfanalysis',
            name='key_customers',
        ),
        migrations.RemoveField(
            model_name='pdfanalysis',
            name='recent_achievements',
        ),
        migrations.RemoveField(
            model_name='pdfanalysis',
            name='target_markets',
        ),
        migrations.AddField(
            model_name='pdfanalysis',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='pdfanalysis',
            name='homepage',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pdfanalysis',
            name='industry',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pdfanalysis',
            name='key_executive',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pdfanalysis',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pdfanalysis',
            name='sales',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='pdfanalysis',
            name='total_funding',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
