# Generated by Django 4.2.20 on 2025-04-17 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout_agent', '0004_rename_business_areas_pdfanalysis_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='url',
            field=models.URLField(max_length=1000),
        ),
    ]
